spring.datasource.url=jdbc:postgresql://localhost:5432/bank_account
spring.datasource.username=bank_account
spring.datasource.password=bank_account

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=always

spring.sql.init.schema-locations=classpath:database/schema.sql
spring.sql.init.data-locations=classpath:database/data.sql

spring.mvc.apiversion.use.header=API-Version
spring.mvc.apiversion.default=1
