CREATE TABLE IF NOT EXISTS account
(
    id              UUID PRIMARY KEY,
    type            VARCHAR(32)    NOT NULL,
    balance         NUMERIC(19, 4) NOT NULL,
    overdraft_limit NUMERIC(19, 4),
    deposit_ceiling NUMERIC(19, 4),
    CONSTRAINT account_type_fields_check CHECK (
        (type = 'BANK_ACCOUNT' AND overdraft_limit IS NOT NULL AND deposit_ceiling IS NULL)
            OR (type = 'SAVINGS_ACCOUNT' AND deposit_ceiling IS NOT NULL AND overdraft_limit IS NULL)
        )
);

CREATE TABLE IF NOT EXISTS operation
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  UUID           NOT NULL REFERENCES account (id),
    type        VARCHAR(32)    NOT NULL,
    amount      NUMERIC(19, 4) NOT NULL,
    balance     NUMERIC(19, 4) NOT NULL,
    occurred_at TIMESTAMP      NOT NULL
);

CREATE INDEX IF NOT EXISTS operation_account_id_occurred_at_idx
    ON operation (account_id, occurred_at);
