services:
  postgres:
    image: postgres:18
    container_name: bank-account-postgres
    environment:
      POSTGRES_DB: bank_account
      POSTGRES_USER: bank_account
      POSTGRES_PASSWORD: bank_account
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
